### PR TITLE
Fix eigenvalues parser for CP2K v9

### PR DESCRIPTION
**Pull request by mbercx**
Fix/simplify the eigenvalue parsing for CP2K v9. The main change is the following:

```python
re.search(r'eached convergence', line):
```

since `Reached` is not capitalized anymore in CP2K v9. Other changes are related to
formatting and putting an upper limit on `markupsafe<2.1` since the latest release
broke the docs build.

### CODE REVIEW

**Comment by mpougin** [comment]
thanks a lot for your input @mbercx. By coincidence, I am currently running cp2k-9 calculations with aiida, so I will test your suggested changes 👍

**Comment by mbercx** [comment]
> thanks a lot for your input @mbercx. By coincidence, I am currently running cp2k-9 calculations with aiida, so I will test your suggested changes 👍

What a wonderful coincidence! I will eagerly await your feedback, then! ^^

**Comment by mpougin** [comment]
hello @mbercx,
I am sure you will be delighted to hear that I couldn't have done it better myself, your changes passed my critical testing. It is working fine now for CP2K-8.1 and CP2K-9.
@yakutovicha could you please merge the branch?

**Review by mpougin — DISMISSED** [review]
working fine for cp2k-8.1 and cp2k-9

**Comment by yakutovicha** [comment]
hey, looks like the pre-commit check is not happy. @mbercx can you please fix that?

**Comment by mbercx** [comment]
> @mbercx can you please fix that?

Eh, sure. Just have to figure out where I actually cloned the package again. 😓

**Comment by mbercx** [comment]
@yakutovicha seems I need you to cut a release for `aiida-cp2k` to fix this, since the addition of the third input argument for `_parse_bands` was added after the `1.3.0` release:

https://github.com/aiidateam/aiida-cp2k/commit/61d4927c9074524a97da207230fcddd053597eec

Once it's out I'll update the dependencies here and the `pre-commit` should be fixed.

@mpougin are you running the `develop` version of `aiida-cp2k`? Else I'd say `_parse_bands` should raise an error. Or you're not running calculations that call that parser, of course. :)

**Comment by mpougin** [comment]
thank you again @mbercx for your contribution here. Yes, you're right, I am running the develop version but not using `_parse_bands` at the moment ;)

**Comment by yakutovicha** [comment]
I will make the cp2k release today. Well, I will try my best.

**Comment by mbercx** [comment]
waitng

**Comment by yakutovicha** [comment]
> waitng

sorry Marnik.

**Comment by yakutovicha** [comment]
I am in the progress of making a release: https://github.com/aiidateam/aiida-cp2k/pull/150. Tests failed ( ¯\\\_(ツ)_/¯), so tomorrow I am going to fix them and then I release the plugin.

**Comment by mpougin** [comment]
thanks @yakutovicha :)

**Comment by yakutovicha** [comment]
released: 1.4.0

**Comment by mbercx** [comment]
Thanks @yakutovicha! To reciprocate I've also prepared a release for `aiida-quantumespresso`, but our automatic deployment on PyPI seems to be failing, sadly. We'll try to fix it asap!

**Comment by mbercx** [comment]
They passed! Praise be! 🥳

**Comment by yakutovicha** [comment]
As requested earlier, I am merging the branch :)

**Review by yakutovicha — APPROVED** [review]

**Comment by mbercx** [comment]
But... I updated the OP with a nice commit message 😭

**Comment by yakutovicha** [comment]
> But... I updated the OP with a nice commit message 😭

sorry, man

**Comment by mbercx** [comment]
> sorry, man

Haha, no biggie 😉

**Pull request merged**
