### PR TITLE
🔧 Modernise package configuration (PEP621)

### PR DESCRIPTION
**Pull request by chrisjsewell**
https://peps.python.org/pep-0621/

https://flit.pypa.io/en/stable/rationale.html

### CODE REVIEW

**Comment by chrisjsewell** [comment]
cc @mpougin

**Comment by mpougin** [comment]
thanks a lot @chrisjsewell :)

**Comment by ltalirz** [comment]
Cheers!

**Comment by mpougin** [comment]
@chrisjsewell now `pip install -e .[testing]` doesn't work anymore as it looks for the `setup.py` file. What do I run instead now?

**Comment by chrisjsewell** [comment]
@mpougin just update your pip version 😉 `pip install -U pip`

**Comment by mpougin** [comment]
ooopsie, thanks 🥇

**Pull request merged**
