### PR TITLE
Add new feature to study adsorption-driven heat pumps

### PR DESCRIPTION
**Pull request by danieleongari**
- [x] handle flexible molecules
- [x] add some flexible molecules
- [x] use CBMC when useful
- [x] compute rosenbluth weight to re-tune the chemical potential
- [x] add IsothermInflectionWorkChain

### CODE REVIEW

**Comment by danieleongari** [comment]
For the record...
All the items in the checklist have been done, 
but the IsothermInflection work chain does not work well as the systems remains trapped in the low density configuration up to p=p0.
I'm currently investigating alternatives to make it more robust, and I won't push until I find a good one.

**Comment by danieleongari** [comment]
Rebasing and preparing minimal examples and documentation to merge to `develop`: I need flexible molecules functionality for other projects

**Comment by ltalirz** [comment]
@danieleongari What is the status of this - should this be merged or do you want to keep this PR open?

**Comment by danieleongari** [comment]
@ltalirz 
> What is the status of this?

I'm wrapping it up just now to merge it, it will be ready to review in a few minutes

**Comment by ltalirz** [comment]
@danieleongari the test failure is indeed not easy to track down

 * tests pass on current `develop` - i.e. it's not an issue of package versions (which this PR does not touch)
 * tests on this branch pass when I run them locally

I'll come back to this once I've made some more progress in the validation

**Comment by ltalirz** [comment]
Oh, I think I see the issue - one of the raspa inputs probably changed, and therefore the result was no longer available in the test data.

I'll check whether that is the case - `aiida-testing` should make sure to show a better error message.

**Pull request merged**
