### PR TITLE
🧪 Fix CI

### PR DESCRIPTION
**Pull request by chrisjsewell**

### CODE REVIEW

**Comment by chrisjsewell** [comment]
cc @mpougin @ltalirz

**Comment by mpougin** [comment]
thanks @chrisjsewell can I merge?

**Comment by chrisjsewell** [comment]
can I merge?

👍

**Comment by mpougin** [comment]
thanks, I think I can close #106 then right?

**Review by mpougin — APPROVED** [review]
Thanks for updating the testing @chrisjsewell and @ltalirz

**Pull request merged**
