### PR TITLE
update aiida-testing

### PR DESCRIPTION
**Pull request by mpougin**
update aiida-testing as discussed with @ltalirz

### CODE REVIEW

**Review by ltalirz — APPROVED** [review]
thanks @mpougin

**Comment by mpougin** [comment]
@ltalirz any idea why all checks fail here?

**Comment by ltalirz** [comment]
the docs/pre-commit failures almost look like a very rare problem on the Github side. It's not able to check out the aiida-lsmo git repository.

**Comment by ltalirz** [comment]
The same tests after merging pass fine https://github.com/lsmo-epfl/aiida-lsmo/commits/develop

**Pull request merged**
