### PR TITLE
Add oxidation state prediction

### PR DESCRIPTION
**Pull request by ltalirz**

### CODE REVIEW

**Comment by ltalirz** [comment]
@danieleongari can you suggest 1-2 interesting mofs to predict the oxidation state, to replace Fe-mof74 and Mg-mof74?

**Comment by danieleongari** [comment]
These two are fine: I would ask @kjappelbaum someone with mixed oxidation states to use as an exotic case, which is useful later if we implement the MAGNETIZATION choice in the `MultistageWorkChain`

**Comment by kjappelbaum** [comment]
can add Cu(I,II)-HKUST-1 which is also in the manuscript and the app

**Comment by kjappelbaum** [comment]
[KAJZIH_freeONLY.cif.txt](https://github.com/lsmo-epfl/aiida-lsmo/files/5696451/KAJZIH_freeONLY.cif.txt)

**Comment by kjappelbaum** [comment]
shall we also store the `str(OXIMACHINE_RUNNER)` somewhere (to have the oximachine and model version)?

**Comment by ltalirz** [comment]
> shall we also store the `str(OXIMACHINE_RUNNER)` somewhere (to have the oximachine and model version)?

We probably need both this and the model name/version

**Comment by ltalirz** [comment]
ah, now I see, it contains it I guess ;-)

**Comment by ltalirz** [comment]
great!

**Pull request merged**
